/* ==========================================================
   NOMU — Single-File App (split into index.html, style.css, app.js)
   ========================================================== */

const $ = (q,root=document)=>root.querySelector(q)
const $$ = (q,root=document)=>Array.from(root.querySelectorAll(q))

/* ---------- i18n (basic) ---------- */
const i18n = {
  lang: localStorage.getItem('nomu.lang') || 'ar',
  t: {
    ar: { 'nav.home':'الرئيسية','nav.login':'تسجيل الدخول','nav.consent':'الموافقة والخصوصية','nav.dashboards':'لوحات القيادة','nav.family':'حساب الأسرة','nav.health':'الصحة','nav.education':'التعليم','nav.nonprofit':'الجمعيات','nav.csr':'القطاع الخاص (CSR)','nav.admin':'اللجنة الوطنية / الإدارة','nav.tools':'أدوات','nav.market':'سوق الرعاية','nav.referrals':'الإحالات','nav.reports':'التقارير','nav.settings':'الإعدادات', 'login.title':'تسجيل الدخول','login.help':'اختر نوع الحساب لتجربة الواجهات.','login.role':'نوع المستخدم','login.region':'المنطقة الإدارية', 'btn.login':'دخول','btn.cancel':'إلغاء','btn.save':'حفظ','btn.print':'طباعة/حفظ PDF','btn.logo':'رفع شعار', 'consent.title':'الموافقة وإدارة الخصوصية (PDPL)','consent.c1':'معالجة بيانات الأم خلال الحمل لأغراض المتابعة الصحية','consent.c2':'مشاركة تقارير الطفل النمائية مع وزارة التعليم','consent.c3':'مشاركة بيانات الدعم الاجتماعي مع الوزارة المختصة','consent.c4':'تلقي تنبيهات وتوصيات عبر البريد/الرسائل', 'labels.childId':'معرف الطفل','labels.type':'نوع الفحص','labels.date':'التاريخ','labels.result':'النتيجة','labels.facility':'المنشأة','labels.from':'من','labels.to':'إلى','labels.priority':'الأولوية','labels.status':'الحالة','labels.review':'مراجعة','labels.goals':'الأهداف','labels.title':'العنوان','labels.kpi':'الهدف (KPI)','labels.ask':'المبلغ المطلوب','labels.owner':'الجهة المالكة','labels.marketId':'معرف المبادرة','labels.company':'الشركة','labels.amount':'المبلغ (ر.س)', 'screening.title':'تسجيل فحص','referral.title':'إنشاء إحالة','iep.title':'إنشاء خطة IEP','market.title':'طرح مبادرة','csr.title':'مساهمة CSR','logo.title':'رفع شعار الجهة', 'reports.export':'تصدير CSV', 'errors.required':'هذا الحقل مطلوب','errors.pattern':'صيغة غير صحيحة','toast.saved':'تم الحفظ','toast.updated':'تم التحديث','toast.apiSaved':'تم الإرسال عبر API','toast.apiFallback':'API غير متاح — حُفظ محليًا', 'region.set':'تم ضبط المنطقة','role.signed':'تم تسجيل الدخول كـ ' },
    en: { 'nav.home':'Home','nav.login':'Sign in','nav.consent':'Consent & Privacy','nav.dashboards':'Dashboards','nav.family':'Family','nav.health':'Health','nav.education':'Education','nav.nonprofit':'Nonprofits','nav.csr':'Private Sector (CSR)','nav.admin':'National Committee / Admin','nav.tools':'Tools','nav.market':'Care Marketplace','nav.referrals':'Referrals','nav.reports':'Reports','nav.settings':'Settings', 'login.title':'Sign in','login.help':'Pick a role to explore the UI.','login.role':'Role','login.region':'Region', 'btn.login':'Sign in','btn.cancel':'Cancel','btn.save':'Save','btn.print':'Print / Save PDF','btn.logo':'Upload Logo', 'consent.title':'Consent & Privacy (PDPL)','consent.c1':'Process maternal data during pregnancy for healthcare follow-up','consent.c2':'Share child developmental reports with MoE','consent.c3':'Share social support data with the relevant ministry','consent.c4':'Receive alerts/recommendations via email/SMS', 'labels.childId':'Child ID','labels.type':'Type','labels.date':'Date','labels.result':'Result','labels.facility':'Facility','labels.from':'From','labels.to':'To','labels.priority':'Priority','labels.status':'Status','labels.review':'Review','labels.goals':'Goals','labels.title':'Title','labels.kpi':'KPI','labels.ask':'Requested Amount','labels.owner':'Owner','labels.marketId':'Market ID','labels.company':'Company','labels.amount':'Amount (SAR)', 'screening.title':'Record Screening','referral.title':'Create Referral','iep.title':'Create IEP','market.title':'Post Initiative','csr.title':'CSR Contribution','logo.title':'Upload Logo', 'reports.export':'Export CSV', 'errors.required':'This field is required','errors.pattern':'Invalid format','toast.saved':'Saved','toast.updated':'Updated','toast.apiSaved':'Sent via API','toast.apiFallback':'API unavailable — saved locally', 'region.set':'Region set','role.signed':'Signed in as ' }
  }
}
function t(key){ const dict=i18n.t[i18n.lang]||i18n.t.ar; return dict[key]||key }
function applyI18n(){ const dict=i18n.t[i18n.lang]||i18n.t.ar; $$('[data-i18n]').forEach(el=>{ const key=el.getAttribute('data-i18n'); if(dict[key]) el.textContent=dict[key] }); document.documentElement.lang = i18n.lang; document.documentElement.dir = (i18n.lang==='ar')?'rtl':'ltr' }

/* ---------- API Bridge ---------- */
const api = { enabled:false, baseUrl:'https://api.example.com', token:null }
async function apiFetch(path,opts={}){ if(!api.enabled){ throw new Error('API_DISABLED') } const res = await fetch(api.baseUrl+path,{ headers:Object.assign({'Content-Type':'application/json', ...(api.token?{Authorization':'Bearer '+api.token}:{})}), ...opts }); if(!res.ok){ const t=await res.text(); throw new Error('API '+res.status+': '+t) } return res.json() }

/* ---------- RBAC ---------- */
const permsByRole = { guest: ['home:view','reports:view','market:view','referrals:view','settings:view'], family:['home:view','family:view','referrals:view','screening:create','settings:view'], health:['home:view','health:view','screening:create','referrals:create','reports:view','settings:view'], education:['home:view','education:view','iep:create','referrals:view','reports:view','settings:view'], nonprofit:['home:view','nonprofit:view','market:create','reports:view','settings:view'], csr:['home:view','csr:view','csr:create','market:view','reports:view','settings:view'], admin:['home:view','admin:view','family:view','health:view','education:view','nonprofit:view','csr:view','market:view','referrals:view','reports:view','settings:view'] }
function can(perm){ const role=store.state.user.role||'guest'; return (permsByRole[role]||[]).includes(perm) }
function enforceRBAC(){ $$('[data-perm]').forEach(el=>{ const need=el.getAttribute('data-perm'); el.hidden=!can(need) }) }

/* ---------- Store ---------- */
const store = { load(){ try{const data=JSON.parse(localStorage.getItem('nomu')||'{}');this.state=Object.assign({ user:{role:'guest',region:'الرياض'}, ui:{logo:null}, consent:{c1:false,c2:false,c3:false,c4:false}, households:[{id:'H-1001', father:'محمد', mother:'سارة', region:'حائل', children:[{id:'C-501', name:'ليان', dob:'2021-03-10'},{id:'C-502', name:'تركي', dob:'2019-11-02'}]}], screenings:[{id:'S-9001', childId:'C-501', type:'نمو نمائي', date:'2025-09-20', result:'سليم', facility:'مركز صحي شمال حائل'}], referrals:[{id:'R-7001', from:'الصحة', to:'التعليم', childId:'C-502', priority:'عادية', status:'قيد المعالجة', created:'2025-09-25'}], ieps:[{id:'IEP-3001', childId:'C-502', goals:'تحسين المهارات اللغوية', review:'2025-12-01'}], nonprofits:[{id:'NPO-10', name:'جمعية نماء للطفولة', region:'حائل', programs:3, beneficiaries:120}], marketplace:[{id:'M-1', title:'جلسات تدخل مبكر لحائل', kpi:'100 طفل خلال 6 أشهر', ask:250000, funded:120000, owner:'جمعية نماء'}, {id:'M-2', title:'فحوص سمع لحديثي الولادة – الشرقية', kpi:'300 وليد', ask:180000, funded:45000, owner:'صحة الشرقية'}], csr:[{id:'CSR-100', company:'شركة الأفق', amount:50000, to:'M-1', date:'2025-10-01'}] }, data)}catch(e){this.state={}} }, save(){localStorage.setItem('nomu',JSON.stringify(this.state))} }
store.load()

/* ---------- Utilities ---------- */
function fmt(n){return new Intl.NumberFormat(i18n.lang==='ar'?'ar-SA':'en-US').format(n)}
function today(){return new Date().toISOString().slice(0,10)}
function toast(msg){ const wrap=$('#toastRegion'); const t=document.createElement('div'); t.setAttribute('role','status'); t.style.cssText='background:#111b;color:#fff;padding:10px 14px;border-radius:12px;backdrop-filter:blur(4px);display:flex;align-items:center;gap:10px'; t.innerHTML=`<span>${msg}</span><button aria-label="Dismiss" style="background:transparent;color:#fff;border:0;font-weight:700">×</button>`; const btn=t.querySelector('button'); btn.onclick=()=>t.remove(); wrap.appendChild(t); setTimeout(()=>t.remove(),3500) }
function escapeHtml(str){return str.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function download(filename, text){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8;'})); a.download=filename; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000) }

/* ---------- Search helpers & quick actions ---------- */
function renderSearch(results){
  const box=$('#searchResults'); if(!box) return;
  if(!results.length){ box.innerHTML=`<div class="empty">${i18n.lang==='ar'?'لا نتائج':'No results'}</div>`; box.classList.add('open'); return }
  box.innerHTML=results.map(r=>`<a href="${r.href}" role="option" onclick="$('#searchResults').classList.remove('open')">${escapeHtml(r.label)}</a>`).join('');
  box.classList.add('open')
}
function globalSearch(q){
  const box=$('#searchResults'); if(!q || q.trim().length<2){ if(box) box.classList.remove('open'); return }
  q=q.trim().toLowerCase(); const res=[];
  store.state.households.forEach(h=>h.children.forEach(c=>{
    if((c.id||'').toLowerCase().includes(q) || (c.name||'').toLowerCase().includes(q)){
      res.push({label:`${c.id} — ${c.name}`, href:`#/family?child=${encodeURIComponent(c.id)}`})
    }
  }));
  store.state.referrals.forEach(r=>{
    if((r.id||'').toLowerCase().includes(q) || (r.childId||'').toLowerCase().includes(q)){
      res.push({label:`${i18n.lang==='ar'?'إحالة':'Referral'} ${r.id} → ${r.to} (${r.childId})`, href:`#/referrals`})
    }
  });
  store.state.marketplace.forEach(m=>{
    if((m.id||'').toLowerCase().includes(q) || (m.title||'').toLowerCase().includes(q) || (m.owner||'').toLowerCase().includes(q)){
      res.push({label:`${i18n.lang==='ar'?'مبادرة':'Initiative'} ${m.id} — ${m.title}`, href:`#/market`})
    }
  });
  renderSearch(res.slice(0,10))
}
document.addEventListener('click',e=>{ const box=$('#searchResults'); if(!box) return; if(!box.contains(e.target) && e.target.id!=='q'){ box.classList.remove('open') } });

/* ---------- Router & Deep-link params ---------- */
function parseHash(){ const [path,q='']=(location.hash.replace('#','')||'/home').split('?'); const params=Object.fromEntries(new URLSearchParams(q).entries()); return {path,params} }
const routes = { '/home': viewHome, '/family': viewFamily, '/health': viewHealth, '/education': viewEducation, '/nonprofit': viewNonprofit, '/csr': viewCSR, '/admin': viewAdmin, '/market': viewMarket, '/referrals': viewReferrals, '/reports': viewReports, '/settings': viewSettings }
function router(){ const {path,params}=parseHash(); $$('a.link').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${path}`)); const el = document.getElementById('view'); el.innerHTML=''; (routes[path]||view404)(el,params); enforceRBAC(); applyI18n(); handleDeepLinks(path,params) }
window.addEventListener('hashchange',router)
function handleDeepLinks(path,params){
  if(params.new==='true'){ if(path==='/market') openModal('modal-market'); if(path==='/referrals') openModal('modal-referral'); if(path==='/health' || path==='/family') openModal('modal-screening') }
  if(params.child){ const el=$('#f_sc_child'); if(el){ el.value=params.child } }
}

/* ---------- Cards helper ---------- */
function kpiCard(title,value,delta){ return `<div class="card third"><span class="k">${title}</span><b class="v">${value}</b><small>${delta||''}</small></div>` }

/* ---------- Views ---------- */
function viewHome(root){
  const totalKids = store.state.households.reduce((a,h)=>a+h.children.length,0),
        screened = store.state.screenings.length,
        referrals = store.state.referrals.length,
        funded = store.state.marketplace.reduce((a,m)=>a+m.funded,0);
  root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'لوحة وطنية مختصرة':'National Overview'}</h2><div class="actions"><span class="tag">${i18n.lang==='ar'?'المنطقة':'Region'}: ${store.state.user.region}</span><button onclick="location.hash='#/reports'">${i18n.lang==='ar'?'عرض التقارير':'Open Reports'}</button></div></div><div class="cards">${kpiCard(i18n.lang==='ar'?'الأطفال في السجل':'Registered Children', fmt(totalKids))}${kpiCard(i18n.lang==='ar'?'فحوص نمائية مُسجلة':'Recorded Screenings', fmt(screened))}${kpiCard(i18n.lang==='ar'?'إحالات نشطة':'Active Referrals', fmt(referrals))}${kpiCard(i18n.lang==='ar'?'تمويل CSR/منح (ر.س)':'CSR/Grants Funding (SAR)', fmt(funded))}<div class="card wide" id="chart"></div><div class="card half"><div class="toolbar"><b>${i18n.lang==='ar'?'آخر المبادرات في سوق الرعاية':'Latest Marketplace Initiatives'}</b><div class="actions"><button class="ghost" onclick="location.hash='#/market'">${i18n.lang==='ar'?'إدارة':'Manage'}</button></div></div>${tableMarketplace(store.state.marketplace.slice(0,5))}</div><div class="card half"><div class="toolbar"><b>${i18n.lang==='ar'?'آخر الإحالات':'Recent Referrals'}</b><div class="actions"><button class="ghost" onclick="location.hash='#/referrals'">${i18n.lang==='ar'?'إدارة':'Manage'}</button></div></div>${tableReferrals(store.state.referrals.slice(0,5))}</div></div>`;
  drawTrend($('#chart'), i18n.lang==='ar'?'أطفال مفحوصون خلال 6 أشهر':'Screened Children (6m)', [40,55,61,70,86,93])
}
function viewFamily(root){ if(!can('family:view')){ return (root.innerHTML = denyCard()) } const h = store.state.households[0]; root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'حساب الأسرة':'Family Account'}</h2><div class="actions">${can('screening:create')?`<button onclick="openModal('modal-screening')">${i18n.lang==='ar'?'حجز/تسجيل فحص':'Book/Record Screening'}</button>`:''}${can('referrals:create')?`<button class="ghost" onclick="openModal('modal-referral')">${i18n.lang==='ar'?'طلب إحالة':'Create Referral'}</button>`:''}</div></div><div class="cards">${kpiCard(i18n.lang==='ar'?'الأطفال':'Children', h.children.length)}${kpiCard(i18n.lang==='ar'?'فحوص مكتملة':'Completed Screenings', store.state.screenings.filter(s=>h.children.some(c=>c.id===s.childId)).length)}${kpiCard(i18n.lang==='ar'?'إحالات مرتبطة':'Related Referrals', store.state.referrals.filter(r=>h.children.some(c=>c.id===r.childId)).length)}<div class="card wide"><div class="toolbar"><b>${i18n.lang==='ar'?'أطفال الأسرة':'Children'}</b><div class="actions"><button class="ghost" onclick="addChild()">${i18n.lang==='ar'?'إضافة طفل':'Add Child'}</button></div></div>${tableKids(h.children)}</div><div class="card half"><b>${i18n.lang==='ar'?'الفحوص':'Screenings'}</b>${tableScreenings(store.state.screenings.filter(s=>h.children.some(c=>c.id===s.childId)))}</div><div class="card half"><b>${i18n.lang==='ar'?'التوصيات الذكية':'Smart Tips'}</b><div class="empty">${i18n.lang==='ar'?'ستظهر التوصيات حسب العمر والفحوص المنجزة.':'Tips will appear based on age and completed screenings.'}</div></div></div>` }
function viewHealth(root){ if(!can('health:view')){ return (root.innerHTML = denyCard()) } root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'وزارة الصحة':'Ministry of Health'}</h2><div class="actions">${can('screening:create')?`<button onclick="openModal('modal-screening')">${i18n.lang==='ar'?'تسجيل فحص':'Record Screening'}</button>`:''}${can('referrals:create')?`<button class="ghost" onclick="openModal('modal-referral')">${i18n.lang==='ar'?'إحالة للتعليم':'Refer to Education'}</button>`:''}</div></div><div class="cards">${kpiCard(i18n.lang==='ar'?'فحوص هذا الشهر':'This Month Screenings', store.state.screenings.filter(s=>s.date.slice(0,7)===today().slice(0,7)).length)}${kpiCard(i18n.lang==='ar'?'متوسط زمن الانتظار (يوم)':'Avg Wait (days)', 7)}${kpiCard(i18n.lang==='ar'?'الإحالات المرسلة':'Referrals Sent', store.state.referrals.filter(r=>r.from==='الصحة').length)}<div class="card wide"><b>${i18n.lang==='ar'?'سجل الفحوص':'Screenings Log'}</b>${tableScreenings(store.state.screenings)}</div></div>` }
function viewEducation(root){ if(!can('education:view')){ return (root.innerHTML = denyCard()) } root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'وزارة التعليم':'Ministry of Education'}</h2><div class="actions">${can('iep:create')?`<button onclick="openModal('modal-iep')">${i18n.lang==='ar'?'إنشاء IEP':'Create IEP'}</button>`:''}</div></div><div class="cards">${kpiCard(i18n.lang==='ar'?'تقارير الجاهزية الصادرة':'Readiness Reports Issued', 42)}${kpiCard(i18n.lang==='ar'?'خطط IEP نشطة':'Active IEPs', store.state.ieps.length)}${kpiCard(i18n.lang==='ar'?'إحالات واردة':'Incoming Referrals', store.state.referrals.filter(r=>r.to==='التعليم').length)}<div class="card half"><b>${i18n.lang==='ar'?'الإحالات الواردة':'Incoming Referrals'}</b>${tableReferrals(store.state.referrals.filter(r=>r.to==='التعليم'))}</div><div class="card half"><b>IEP</b>${tableIEP(store.state.ieps)}</div></div>` }
function viewNonprofit(root){ if(!can('nonprofit:view')){ return (root.innerHTML = denyCard()) } root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'الجمعيات':'Nonprofits'}</h2><div class="actions">${can('market:create')?`<button onclick="openModal('modal-market')">${i18n.lang==='ar'?'طرح مبادرة':'Post Initiative'}</button>`:''}</div></div><div class="cards">${kpiCard(i18n.lang==='ar'?'برامج فعّالة':'Active Programs', 5)}${kpiCard(i18n.lang==='ar'?'المستفيدون':'Beneficiaries', 120)}${kpiCard(i18n.lang==='ar'?'المتطوعون':'Volunteers', 48)}<div class="card wide"><b>${i18n.lang==='ar'?'جمعيات مسجلة':'Registered NGOs'}</b>${tableNPOs(store.state.nonprofits)}</div></div>` }
function viewCSR(root){ if(!can('csr:view')){ return (root.innerHTML = denyCard()) } root.innerHTML = `<div class="toolbar"><h2>CSR</h2><div class="actions">${can('csr:create')?`<button onclick="openModal('modal-csr')">${i18n.lang==='ar'?'مساهمة جديدة':'New Contribution'}</button>`:''}</div></div><div class="cards">${kpiCard(i18n.lang==='ar'?'إجمالي المساهمات (ر.س)':'Total Contributions (SAR)', fmt(store.state.csr.reduce((a,c)=>a+c.amount,0)))}${kpiCard(i18n.lang==='ar'?'عدد الشركات':'Companies', new Set(store.state.csr.map(c=>c.company)).size)}${kpiCard(i18n.lang==='ar'?'مبادرات مدعومة':'Supported Initiatives', new Set(store.state.csr.map(c=>c.to)).size)}<div class="card half"><b>${i18n.lang==='ar'?'المساهمات':'Contributions'}</b>${tableCSR(store.state.csr)}</div><div class="card half"><b>${i18n.lang==='ar'?'سوق الرعاية':'Marketplace'}</b>${tableMarketplace(store.state.marketplace)}</div></div>` }
function viewAdmin(root){ if(!can('admin:view')){ return (root.innerHTML = denyCard()) } root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'اللجنة الوطنية / إدارة المنصة':'National Committee / Platform Admin'}</h2><div class="actions"><button class="warn" onclick="seedDemo()">${i18n.lang==='ar'?'ملء بيانات تجريبية':'Seed Demo'}</button><button class="danger" onclick="wipe()">${i18n.lang==='ar'?'مسح البيانات':'Wipe Data'}</button></div></div><div class="cards">${kpiCard(i18n.lang==='ар'?'مستخدمون نشطون (تجريبي)':'Active Users (Demo)', 312)}${kpiCard(i18n.lang==='ar'?'عمليات تكامل ناجحة':'Successful Integrations', 99+'%')}${kpiCard(i18n.lang==='ar'?'أمان وامتثال':'Security & Compliance', 'PDPL / MFA')}<div class="card half"><b>${i18n.lang==='ar'?'إعدادات عامة':'General Settings'}</b><div class="grid two"><div class="field"><label>${i18n.lang==='ar'?'منطقة افتراضية':'Default Region'}</label><select onchange="setRegion(this.value)"><option ${store.state.user.region==='الرياض'?'selected':''}>الرياض</option><option ${store.state.user.region==='حائل'?'selected':''}>حائل</option><option ${store.state.user.region==='الشرقية'?'selected':''}>الشرقية</option></select></div><div class="field"><label>${i18n.lang==='ar'?'لغة الواجهة':'Interface Language'}</label><select id="langSel" onchange="setLang(this.value)"><option value="ar" ${i18n.lang==='ar'?'selected':''}>العربية</option><option value="en" ${i18n.lang==='en'?'selected':''}>English</option></select></div><div class="field"><label>${i18n.lang==='ar'?'شعار الواجهة':'Logo'}</label><div class="actions"><button class="ghost" onclick="openModal('modal-logo')">${i18n.lang==='ar'?'رفع شعار':'Upload Logo'}</button></div></div></div></div><div class="card half"><b>${i18n.lang==='ar'?'سياسات الخصوصية':'Privacy Policies'}</b><div class="grid"><div class="tag">PoLP</div><div class="tag">Audit Trail</div><div class="tag">Encryption</div><div class="tag">Consent</div></div></div></div>` }
function viewMarket(root){ if(!can('market:view')) return (root.innerHTML=denyCard()); root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'سوق الرعاية':'Care Marketplace'}</h2><div class="actions">${can('market:create')?`<button onclick="openModal('modal-market')">${i18n.lang==='ar'?'مبادرة جديدة':'New Initiative'}</button>`:''}</div></div><div class="cards"><div class="card wide">${tableMarketplace(store.state.marketplace,true)}</div></div>` }
function viewReferrals(root){ if(!can('referrals:view')) return (root.innerHTML=denyCard()); root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'الإحالات':'Referrals'}</h2><div class="actions">${can('referrals:create')?`<button onclick="openModal('modal-referral')">${i18n.lang==='ar'?'إحالة جديدة':'New Referral'}</button>`:''}</div></div><div class="cards"><div class="card wide">${tableReferrals(store.state.referrals,true)}</div></div>` }
function viewReports(root){ if(!can('reports:view')) return (root.innerHTML=denyCard()); const totals={kids:store.state.households.reduce((a,h)=>a+h.children.length,0), scr:store.state.screenings.length, ref:store.state.referrals.length}; root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'التقارير':'Reports'}</h2><div class="actions"><button class="ghost" onclick="window.print()" data-i18n="btn.print">طباعة/حفظ PDF</button><button onclick="exportCSVs()">${t('reports.export')}</button></div></div><div class="cards">${kpiCard(i18n.lang==='ar'?'إجمالي الأطفال':'Total Children', fmt(totals.kids))}${kpiCard(i18n.lang==='ar'?'الفحوص':'Screenings', fmt(totals.scr))}${kpiCard(i18n.lang==='ar'?'الإحالات':'Referrals', fmt(totals.ref))}<div class="card wide" id="chart2"></div><div class="card wide"><b>${i18n.lang==='ar'?'سجل كامل':'Full Dump'}</b><pre style="white-space:pre-wrap;background:#0f172a;border:1px solid var(--border);padding:12px;border-radius:12px;direction:ltr">${escapeHtml(JSON.stringify(store.state,null,2))}</pre></div></div>`; drawTrend($('#chart2'), i18n.lang==='ar'?'تمويل شهري (ر.س)':'Monthly Funding (SAR)', [20,30,15,60,40,80]) }
function viewSettings(root){ root.innerHTML = `<div class="toolbar"><h2>${i18n.lang==='ar'?'الإعدادات':'Settings'}</h2></div><div class="cards"><div class="card half"><b>${i18n.lang==='ar'?'إدارة الموافقات':'Consent Management'}</b><p class="help">${i18n.lang==='ar'?'نفس عناصر نافذة الخصوصية.':'Same as consent modal.'}</p><div class="actions"><button onclick="openConsent()">${i18n.lang==='ar'?'فتح':'Open'}</button></div></div><div class="card half"><b>${i18n.lang==='ar'?'جلسة المستخدم':'User Session'}</b><div class="actions"><button class="ghost" onclick="openLogin()">${i18n.lang==='ar'?'تبديل الدور':'Switch Role'}</button><button class="danger" onclick="wipe()">${i18n.lang==='ar'?'مسح البيانات المحلية':'Clear Local Data'}</button></div></div><div class="card wide"><b>${i18n.lang==='ar'?'وضع التكامل مع API':'API Bridge'}</b><div class="grid two"><div class="field"><label><input type="checkbox" id="api_enabled"> ${i18n.lang==='ar'?'تفعيل وضع API':'Enable API Mode'}</label><div class="help">${i18n.lang==='ar'?'عند التفعيل، يُستخدم REST بدلاً من LocalStorage.':'When enabled, REST replaces LocalStorage.'}</div></div><div class="field"><label>Base URL</label><input id="api_base" placeholder="https://api.example.com" /></div><div class="field"><label>Token</label><input id="api_token" placeholder="Bearer ..." /></div><div class="field"><label>${i18n.lang==='ar'?'الشعار':'Logo'}</label><div class="actions"><button class="ghost" onclick="openModal('modal-logo')">${i18n.lang==='ar'?'رفع شعار':'Upload Logo'}</button></div></div></div><div class="actions"><button onclick="applyApiSettings()">${i18n.lang==='ar'?'حفظ إعدادات API':'Save API Settings'}</button></div></div></div>`; $('#api_enabled').checked=api.enabled; $('#api_base').value=api.baseUrl; $('#api_token').value=api.token||'' }
function view404(root){ root.innerHTML = `<div class="empty"><b>${i18n.lang==='ar'?'الصفحة غير موجودة':'Page Not Found'}</b><div>${i18n.lang==='ar'?'المسار:':'Path:'} ${location.hash}</div></div>` }

function denyCard(){ return `<div class="empty"><b>${i18n.lang==='ar'?'صلاحيات غير كافية':'Insufficient permissions'}</b></div>` }

/* ---------- Tables ---------- */
function tableKids(items){ return `<table><thead><tr><th>${i18n.lang==='ar'?'الرقم':'ID'}</th><th>${i18n.lang==='ar'?'الاسم':'Name'}</th><th>${i18n.lang==='ar'?'الميلاد':'Birthdate'}</th></tr></thead><tbody>${items.map(c=>`<tr><td>${c.id}</td><td>${c.name}</td><td>${c.dob}</td></tr>`).join('')}</tbody></table>` }
function tableScreenings(items){ return `<table><thead><tr><th>${i18n.lang==='ar'?'المعرف':'ID'}</th><th>${i18n.lang==='ar'?'الطفل':'Child'}</th><th>${i18n.lang==='ar'?'النوع':'Type'}</th><th>${i18n.lang==='ar'?'التاريخ':'Date'}</th><th>${i18n.lang==='ar'?'النتيجة':'Result'}</th><th>${i18n.lang==='ar'?'المنشأة':'Facility'}</th></tr></thead><tbody>${items.map(s=>`<tr><td>${s.id}</td><td>${s.childId}</td><td>${s.type}</td><td>${s.date}</td><td>${s.result}</td><td>${s.facility}</td></tr>`).join('')}</tbody></table>` }
function tableReferrals(items,actions){ return `<table><thead><tr><th>${i18n.lang==='ar'?'المعرف':'ID'}</th><th>${i18n.lang==='ar'?'من':'From'}</th><th>${i18n.lang==='ar'?'إلى':'To'}</th><th>${i18n.lang==='ar'?'الطفل':'Child'}</th><th>${i18n.lang==='ar'?'الأولوية':'Priority'}</th><th>${i18n.lang==='ar'?'الحالة':'Status'}</th><th>${i18n.lang==='ar'?'التاريخ':'Date'}</th>${actions?'<th></th>':''}</tr></thead><tbody>${items.map(r=>`<tr><td>${r.id}</td><td>${r.from}</td><td>${r.to}</td><td>${r.childId}</td><td>${r.priority}</td><td>${r.status}</td><td>${r.created}</td>${actions?`<td><button class='ghost' onclick="updateReferral('${r.id}')">${i18n.lang==='ar'?'تحديث':'Update'}</button></td>`:''}</tr>`).join('')}</tbody></table>` }
function tableIEP(items){ return `<table><thead><tr><th>${i18n.lang==='ar'?'المعرف':'ID'}</th><th>${i18n.lang==='ar'?'الطفل':'Child'}</th><th>${i18n.lang==='ar'?'الأهداف':'Goals'}</th><th>${i18n.lang==='ar'?'مراجعة':'Review'}</th></tr></thead><tbody>${items.map(i=>`<tr><td>${i.id}</td><td>${i.childId}</td><td>${i.goals}</td><td>${i.review}</td></tr>`).join('')}</tbody></table>` }
function tableNPOs(items){ return `<table><thead><tr><th>${i18n.lang==='ar'?'المعرف':'ID'}</th><th>${i18n.lang==='ar'?'الاسم':'Name'}</th><th>${i18n.lang==='ar'?'المنطقة':'Region'}</th><th>${i18n.lang==='ar'?'برامج':'Programs'}</th><th>${i18n.lang==='ar'?'مستفيدون':'Beneficiaries'}</th></tr></thead><tbody>${items.map(n=>`<tr><td>${n.id||'-'}</td><td>${n.name}</td><td>${n.region}</td><td>${n.programs}</td><td>${n.beneficiaries}</td></tr>`).join('')}</tbody></table>` }
function tableCSR(items){ return `<table><thead><tr><th>${i18n.lang==='ar'?'المعرف':'ID'}</th><th>${i18n.lang==='ar'?'الشركة':'Company'}</th><th>${i18n.lang==='ar'?'المبلغ':'Amount'}</th><th>${i18n.lang==='ar'?'المبادرة':'Initiative'}</th><th>${i18n.lang==='ar'?'التاريخ':'Date'}</th></tr></thead><tbody>${items.map(c=>`<tr><td>${c.id}</td><td>${c.company}</td><td>${fmt(c.amount)}</td><td>${c.to}</td><td>${c.date}</td></tr>`).join('')}</tbody></table>` }
function tableMarketplace(items,actions){ return `<table><thead><tr><th>${i18n.lang==='ar'?'المعرف':'ID'}</th><th>${i18n.lang==='ar'?'المبادرة':'Initiative'}</th><th>KPI</th><th>${i18n.lang==='ar'?'المطلوب':'Requested'}</th><th>${i18n.lang==='ar'?'الممول':'Funded'}</th><th>${i18n.lang==='ar'?'الجهة':'Owner'}</th>${actions?'<th></th>':''}</tr></thead><tbody>${items.map(m=>`<tr><td>${m.id}</td><td>${m.title}</td><td>${m.kpi}</td><td>${fmt(m.ask)}</td><td>${fmt(m.funded)}</td><td>${m.owner}</td>${actions?`<td><button class='ghost' onclick="fund('${m.id}')">${i18n.lang==='ar'?'تمويل':'Fund'}</button></td>`:''}</tr>`).join('')}</tbody></table>` }

/* ---------- Chart with points & axis ---------- */
function drawTrend(el,title,data){
  const w=el.clientWidth||600,h=180,p=24;
  const min=Math.min(...data),max=Math.max(...data);
  const rng=(max-min)||1;
  const toX=i=>p + (i*(w-2*p))/(data.length-1);
  const toY=v=>h-p - ((v-min)*(h-2*p))/rng;
  const pts=data.map((v,i)=>`${toX(i)},${toY(v)}`).join(' ');
  const ticks=5; let axis='';
  for(let i=0;i<=ticks;i++){
    const y=p + (i*(h-2*p))/ticks; const val=(max - (i*rng)/ticks).toFixed(0);
    axis+=`<line x1="${p-6}" y1="${y}" x2="${w-p}" y2="${y}" stroke="#27324d" stroke-width="1" opacity="0.4"/><text x="${w-p+6}" y="${y+4}" font-size="10" fill="#a7b0c3">${val}</text>`
  }
  const circles=data.map((v,i)=>`<circle cx="${toX(i)}" cy="${toY(v)}" r="3.5"/><text x="${toX(i)+6}" y="${toY(v)-6}" font-size="10" fill="#a7b0c3">${v}</text>`).join('');
  el.innerHTML = `<b>${title}</b><svg viewBox="0 0 ${w} ${h}" width="100%" height="${h}" role="img" aria-label="${title}"><rect x="${p-8}" y="${p-8}" width="${w-2*(p-8)}" height="${h-2*(p-8)}" fill="none" stroke="#27324d" opacity=".4"/><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="3"/>${circles}${axis}</svg>`
}

/* ---------- Modal focus trap + Esc ---------- */
let lastFocused=null; let activeModal=null;
function openModal(id){ const m=$('#'+id); if(!m) return; activeModal=m; m.classList.add('open'); lastFocused=document.activeElement; const focusables=$$('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])',m); (focusables[0]||m).focus(); function trap(e){ if(e.key==='Tab'){ const first=focusables[0], last=focusables[focusables.length-1]; if(e.shiftKey && document.activeElement===first){ last.focus(); e.preventDefault() } else if(!e.shiftKey && document.activeElement===last){ first.focus(); e.preventDefault() } } if(e.key==='Escape'){ closeModal(id) } } m.addEventListener('keydown',trap); m._trap=trap }
function closeModal(id){ const m=$('#'+id); if(!m) return; m.classList.remove('open'); if(m._trap){ m.removeEventListener('keydown',m._trap); m._trap=null } (lastFocused||document.body).focus(); activeModal=null }
window.addEventListener('keydown',e=>{ if(e.key==='Escape' && activeModal){ closeModal(activeModal.id) } })

/* ---------- Validation helpers ---------- */
function clearErrors(scope=document){ $$('[data-err]',scope).forEach(el=>el.textContent='') }
function setError(input,msg){ const id=input.id; const el=$(`[data-err="${id}"]`); if(el){ el.textContent=msg } }
function checkRequired(input){ if(input.hasAttribute('data-req') && !input.value.trim()){ setError(input,t('errors.required')); return false } return true }
function checkPattern(input){ const pat=input.getAttribute('data-pattern'); if(pat){ const re=new RegExp(pat); if(!re.test(input.value.trim())){ setError(input,t('errors.pattern')); return false } } return true }
function validateForm(ids){ clearErrors(); let ok=true; ids.forEach(id=>{ const el=$('#'+id); if(!el) return; ok = checkRequired(el) && checkPattern(el) && ok }); return ok }

/* ---------- Session & actions ---------- */
function openLogin(){
  openModal('modal-login');
  const r=store.state.user||{};
  if($('#loginRole')) $('#loginRole').value=r.role||'guest';
  if($('#loginRegion')) $('#loginRegion').value=r.region||'الرياض';
}
function openConsent(){
  const c=store.state.consent||{};
  ['c1','c2','c3','c4'].forEach(k=>{ const el=$('#'+k); if(el) el.checked=!!c[k] });
  openModal('modal-consent');
}
function doLogin(){ const role=$('#loginRole').value; const region=$('#loginRegion').value; if(!validateForm(['loginRole','loginRegion'])) return; store.state.user={role,region}; store.save(); $('#roleTag').textContent=t('role.signed')+role; closeModal('modal-login'); toast(t('role.signed')+role); enforceRBAC(); router() }
function saveConsent(){ store.state.consent={c1:$('#c1').checked,c2:$('#c2').checked,c3:$('#c3').checked,c4:$('#c4').checked}; store.save(); closeModal('modal-consent'); toast(t('toast.saved')) }

function submitScreening(){ if(!validateForm(['f_sc_child','f_sc_date'])) return; const id='S-'+Math.floor(Math.random()*1e5); const payload={ id, childId:$('#f_sc_child').value, type:$('#f_sc_type').value, date:$('#f_sc_date').value, result:$('#f_sc_result').value||'—', facility:$('#f_sc_facility').value||store.state.user.region+'/مركز صحي' }; if(api.enabled){ apiFetch('/screenings',{method:'POST',body:JSON.stringify(payload)}).then(()=>toast(t('toast.apiSaved'))).catch(()=>{store.state.screenings.push(payload);store.save();toast(t('toast.apiFallback'))}).finally(()=>{closeModal('modal-screening');router()}) } else { store.state.screenings.push(payload); store.save(); closeModal('modal-screening'); toast(t('toast.saved')); router() } }
function submitReferral(){ if(!validateForm(['f_ref_child','f_ref_date'])) return; const id='R-'+Math.floor(Math.random()*1e5); const payload={ id, from:$('#f_ref_from').value, to:$('#f_ref_to').value, childId:$('#f_ref_child').value, priority:$('#f_ref_pri').value, status:$('#f_ref_status').value, created:$('#f_ref_date').value }; if(api.enabled){ apiFetch('/referrals',{method:'POST',body:JSON.stringify(payload)}).then(()=>toast(t('toast.apiSaved'))).catch(()=>{store.state.referrals.push(payload);store.save();toast(t('toast.apiFallback'))}).finally(()=>{closeModal('modal-referral');router()}) } else { store.state.referrals.push(payload); store.save(); closeModal('modal-referral'); toast(t('toast.saved')); router() } }
function updateReferral(id){ const r=store.state.referrals.find(x=>x.id===id); if(!r) return; const st=prompt(i18n.lang==='ar'?'تحديث الحالة:':'Update status:', r.status)||r.status; r.status=st; store.save(); toast(t('toast.updated')); router() }
function submitIEP(){ if(!validateForm(['f_iep_child','f_iep_review'])) return; const id='IEP-'+Math.floor(Math.random()*1e5); const payload={ id, childId:$('#f_iep_child').value, goals:$('#f_iep_goals').value||'Goals', review:$('#f_iep_review').value }; if(api.enabled){ apiFetch('/iep',{method:'POST',body:JSON.stringify(payload)}).then(()=>toast(t('toast.apiSaved'))).catch(()=>{store.state.ieps.push(payload);store.save();toast(t('toast.apiFallback'))}).finally(()=>{closeModal('modal-iep');router()}) } else { store.state.ieps.push(payload); store.save(); closeModal('modal-iep'); toast(t('toast.saved')); router() } }
function submitMarket(){ if(!validateForm(['f_m_title','f_m_kpi','f_m_ask','f_m_owner'])) return; const id='M-'+Math.floor(Math.random()*1e5); const payload={ id, title:$('#f_m_title').value, kpi:$('#f_m_kpi').value, ask:parseInt($('#f_m_ask').value||'0',10), funded:0, owner:$('#f_m_owner').value||'جمعية' }; if(api.enabled){ apiFetch('/market',{method:'POST',body:JSON.stringify(payload)}).then(()=>toast(t('toast.apiSaved'))).catch(()=>{store.state.marketplace.push(payload);store.save();toast(t('toast.apiFallback'))}).finally(()=>{closeModal('modal-market');router()}) } else { store.state.marketplace.push(payload); store.save(); closeModal('modal-market'); toast(t('toast.saved')); router() } }
function submitCSR(){ if(!validateForm(['f_csr_to','f_csr_company','f_csr_amount','f_csr_date'])) return; const id='CSR-'+Math.floor(Math.random()*1e5); const payload={ id, company:$('#f_csr_company').value||'Company', amount:parseInt($('#f_csr_amount').value||'0',10), to:$('#f_csr_to').value, date:$('#f_csr_date').value }; if(api.enabled){ apiFetch('/csr',{method:'POST',body:JSON.stringify(payload)}).then(()=>toast(t('toast.apiSaved'))).catch(()=>{store.state.csr.push(payload); const m=store.state.marketplace.find(x=>x.id===payload.to); if(m) m.funded+=payload.amount; store.save(); toast(t('toast.apiFallback'))}).finally(()=>{closeModal('modal-csr');router()}) } else { store.state.csr.push(payload); const m=store.state.marketplace.find(x=>x.id===payload.to); if(m) m.funded+=payload.amount; store.save(); closeModal('modal-csr'); toast(t('toast.saved')); router() } }
function fund(id){ const amount=parseInt(prompt(i18n.lang==='ar'?'مبلغ التمويل (ر.س):':'Funding amount (SAR):','10000')||'0',10); if(!amount) return; const payload={ id:'CSR-'+Math.floor(Math.random()*1e5), company:'Supporter', amount, to:id, date:today() }; if(api.enabled){ apiFetch('/csr',{method:'POST',body:JSON.stringify(payload)}).catch(()=>{}); } store.state.csr.push(payload); const m=store.state.marketplace.find(x=>x.id===id); if(m) m.funded+=amount; store.save(); toast(t('toast.updated')); router() }
function addChild(){ const h=store.state.households[0]; const id='C-'+Math.floor(Math.random()*1e4); const name=prompt(i18n.lang==='ar'?'اسم الطفل:':'Child name:','طفلي'); const dob=prompt(i18n.lang==='ar'?'تاريخ الميلاد (YYYY-MM-DD):':'Birthdate (YYYY-MM-DD):',today()); if(!name) return; h.children.push({id,name,dob}); store.save(); toast(t('toast.saved')); router() }

/* ---------- Logo upload ---------- */
function uploadLogo(){ const f=$('#logoFile').files[0]; if(!f) return; if(f.size>1.5*1024*1024){ toast(i18n.lang==='ar'?'حجم الشعار كبير':'Logo too large'); return } const r=new FileReader(); r.onload=e=>{ store.state.ui.logo=e.target.result; store.save(); $('#logo').src=store.state.ui.logo; closeModal('modal-logo'); toast(i18n.lang==='ar'?'تم تحديث الشعار':'Logo updated') }; r.readAsDataURL(f) }

/* ---------- CSV Exports (with meta row) ---------- */
function toCSV(rows, headers){ const esc=v=>(''+(v??'')).replaceAll('"','""'); const head=headers.join(','); const body=rows.map(r=>headers.map(h=>`"${esc(r[h])}"`).join(',')).join('\n'); return head+'\n'+body }
function exportCSVs(){ const meta=`generated_at,role,region
"${new Date().toISOString()}","${store.state.user.role}","${store.state.user.region}"

`; const sCSV=meta+toCSV(store.state.screenings,["id","childId","type","date","result","facility"]); download('screenings.csv',sCSV); const rCSV=meta+toCSV(store.state.referrals,["id","from","to","childId","priority","status","created"]); download('referrals.csv',rCSV); const cCSV=meta+toCSV(store.state.csr,["id","company","amount","to","date"]); download('csr.csv',cCSV); toast(i18n.lang==='ar'?'تم تصدير CSV':'CSV exported') }

/* ---------- Settings helpers ---------- */
function setRegion(region){store.state.user.region=region;store.save();toast(t('region.set'));router()}
function setLang(lang){ i18n.lang=lang; localStorage.setItem('nomu.lang',lang); applyI18n(); router() }
function applyApiSettings(){ api.enabled=$('#api_enabled').checked; api.baseUrl=$('#api_base').value||api.baseUrl; api.token=$('#api_token').value||null; toast(api.enabled?(i18n.lang==='ar'?'تم تفعيل وضع API':'API mode enabled'):(i18n.lang==='ar'?'تم تعطيل وضع API':'API mode disabled')) }

/* ---------- Admin helpers ---------- */
function seedDemo(){
  const rand=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;
  for(let i=0;i<3;i++){
    const cid='C-'+rand(600,999);
    const name='طفل '+cid.slice(2);
    const dob=`2020-0${rand(1,9)}-${String(rand(10,28)).padStart(2,'0')}`;
    const scId='S-'+rand(10000,99999);
    store.state.households[0].children.push({id:cid,name,dob});
    store.state.screenings.push({id:scId,childId:cid,type:'نمو نمائي',date:today(),result:'سليم',facility:'مركز صحي '+store.state.user.region});
  }
  store.save(); toast(t('toast.saved')); router();
}
function wipe(){ localStorage.removeItem('nomu'); toast(i18n.lang==='ar'?'تم مسح البيانات — سيتم إعادة التحميل':'Cleared local data — reloading'); setTimeout(()=>location.reload(),600) }

/* ---------- Init ---------- */
function initLogo(){ if(store.state.ui.logo){ $('#logo').src=store.state.ui.logo; $('#logo').classList.remove('ph') } }
router(); applyI18n(); enforceRBAC(); initLogo();
$('#roleTag').textContent = (i18n.lang==='ar'?'دور: ':'Role: ')+ (store.state.user.role||'guest')